# Generated by Django 3.2 on 2021-04-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
