# Generated by Django 3.2 on 2021-10-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_csv_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
